# Generated by Django 5.2.16 on 2026-07-14 01:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Constructora', max_length=100, verbose_name='nombre del sitio')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('contact_whatsapp', models.CharField(blank=True, help_text='Número con código de país, sin signos. Ej: 50588887777', max_length=30, verbose_name='WhatsApp')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='dirección (línea 1)')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='dirección (línea 2)')),
                ('city', models.CharField(default='Managua', max_length=100, verbose_name='ciudad')),
                ('department', models.CharField(default='Managua', max_length=100, verbose_name='departamento')),
                ('country', models.CharField(default='Nicaragua', max_length=100, verbose_name='país')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('google_maps_embed_url', models.URLField(blank=True, verbose_name='URL embed de Google Maps')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='título del hero')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='subtítulo del hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='core/hero/', verbose_name='imagen del hero')),
                ('hero_cta_label', models.CharField(blank=True, max_length=50, verbose_name='texto del CTA')),
                ('hero_cta_url', models.CharField(blank=True, max_length=200, verbose_name='URL del CTA')),
                ('footer_text', models.TextField(blank=True, verbose_name='texto del footer')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('home_featured_photos', models.ManyToManyField(blank=True, help_text='Fotos seleccionadas de cualquier obra para mostrar en el home.', related_name='featured_on_home', to='portfolio.workphoto', verbose_name='fotos destacadas del home')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCoreConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('site_name', models.CharField(default='Constructora', max_length=100, verbose_name='nombre del sitio')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='eslogan')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='logo')),
                ('favicon', models.TextField(blank=True, max_length=100, null=True, verbose_name='favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('contact_whatsapp', models.CharField(blank=True, help_text='Número con código de país, sin signos. Ej: 50588887777', max_length=30, verbose_name='WhatsApp')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='dirección (línea 1)')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='dirección (línea 2)')),
                ('city', models.CharField(default='Managua', max_length=100, verbose_name='ciudad')),
                ('department', models.CharField(default='Managua', max_length=100, verbose_name='departamento')),
                ('country', models.CharField(default='Nicaragua', max_length=100, verbose_name='país')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('google_maps_embed_url', models.URLField(blank=True, verbose_name='URL embed de Google Maps')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='título del hero')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='subtítulo del hero')),
                ('hero_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='imagen del hero')),
                ('hero_cta_label', models.CharField(blank=True, max_length=50, verbose_name='texto del CTA')),
                ('hero_cta_url', models.CharField(blank=True, max_length=200, verbose_name='URL del CTA')),
                ('footer_text', models.TextField(blank=True, verbose_name='texto del footer')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuración del sitio',
                'verbose_name_plural': 'historical configuración del sitio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
