# Generated by Django 5.2.16 on 2026-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreconfig',
            name='stat_departments',
            field=models.CharField(blank=True, default='12', help_text='Departamentos donde han construido. Ej: "12"', max_length=10, verbose_name='departamentos'),
        ),
        migrations.AddField(
            model_name='coreconfig',
            name='stat_km',
            field=models.CharField(blank=True, default='200+', help_text='Km de carreteras u obras lineales. Ej: "200+"', max_length=10, verbose_name='km construidos'),
        ),
        migrations.AddField(
            model_name='coreconfig',
            name='stat_works',
            field=models.CharField(blank=True, default='150+', help_text='Ej: "150+"', max_length=10, verbose_name='cantidad de obras'),
        ),
        migrations.AddField(
            model_name='coreconfig',
            name='stat_years',
            field=models.CharField(blank=True, default='25+', help_text='Número grande mostrado en el home. Ej: "25+"', max_length=10, verbose_name='años de experiencia'),
        ),
        migrations.AddField(
            model_name='historicalcoreconfig',
            name='stat_departments',
            field=models.CharField(blank=True, default='12', help_text='Departamentos donde han construido. Ej: "12"', max_length=10, verbose_name='departamentos'),
        ),
        migrations.AddField(
            model_name='historicalcoreconfig',
            name='stat_km',
            field=models.CharField(blank=True, default='200+', help_text='Km de carreteras u obras lineales. Ej: "200+"', max_length=10, verbose_name='km construidos'),
        ),
        migrations.AddField(
            model_name='historicalcoreconfig',
            name='stat_works',
            field=models.CharField(blank=True, default='150+', help_text='Ej: "150+"', max_length=10, verbose_name='cantidad de obras'),
        ),
        migrations.AddField(
            model_name='historicalcoreconfig',
            name='stat_years',
            field=models.CharField(blank=True, default='25+', help_text='Número grande mostrado en el home. Ej: "25+"', max_length=10, verbose_name='años de experiencia'),
        ),
    ]
