# Generated by Django 5.2.16 on 2026-07-14 01:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(help_text='URL amigable. Ej: "quienes-somos". Se genera automáticamente.', max_length=200, verbose_name='slug')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('body', models.JSONField(blank=True, default=list, verbose_name='contenido')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO. Si está vacío, se usa el título de la página.', max_length=200, verbose_name='meta título')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para SEO. Máximo 300 caracteres.', max_length=300, verbose_name='meta descripción')),
                ('og_image', models.TextField(blank=True, help_text='Imagen para redes sociales. Si está vacía, se usa la por defecto.', max_length=100, null=True, verbose_name='imagen Open Graph')),
                ('is_in_menu', models.BooleanField(default=False, verbose_name='mostrar en menú')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='orden en menú')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado el')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical página',
                'verbose_name_plural': 'historical páginas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(help_text='URL amigable. Ej: "quienes-somos". Se genera automáticamente.', max_length=200, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('body', models.JSONField(blank=True, default=list, verbose_name='contenido')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO. Si está vacío, se usa el título de la página.', max_length=200, verbose_name='meta título')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para SEO. Máximo 300 caracteres.', max_length=300, verbose_name='meta descripción')),
                ('og_image', models.ImageField(blank=True, help_text='Imagen para redes sociales. Si está vacía, se usa la por defecto.', null=True, upload_to='pages/og/', verbose_name='imagen Open Graph')),
                ('is_in_menu', models.BooleanField(default=False, verbose_name='mostrar en menú')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='orden en menú')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
