# Generated by Django 5.2.16 on 2026-07-14 01:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('client', models.CharField(blank=True, help_text='Opcional. A veces el cliente es confidencial.', max_length=200, verbose_name='cliente')),
                ('location', models.CharField(help_text='Ej: "Managua, Nicaragua"', max_length=200, verbose_name='ubicación')),
                ('year', models.PositiveIntegerField(verbose_name='año')),
                ('description_short', models.CharField(blank=True, help_text='Para cards y listados. Máximo 300 caracteres.', max_length=300, verbose_name='descripción corta')),
                ('body', models.JSONField(blank=True, default=list, help_text='Bloques de contenido reusables (mismos que las páginas).', verbose_name='contenido')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado en home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='portfolio.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['-year', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/', verbose_name='imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='pie de foto')),
                ('alt_text', models.CharField(help_text='Requerido para accesibilidad. Describe la imagen.', max_length=200, verbose_name='texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.portfoliowork', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'foto de obra',
                'verbose_name_plural': 'fotos de obra',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='cover_photo',
            field=models.ForeignKey(blank=True, help_text='Si está vacía, se usa la primera foto de la galería.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.workphoto', verbose_name='foto de portada'),
        ),
        migrations.CreateModel(
            name='HistoricalPortfolioWork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('client', models.CharField(blank=True, help_text='Opcional. A veces el cliente es confidencial.', max_length=200, verbose_name='cliente')),
                ('location', models.CharField(help_text='Ej: "Managua, Nicaragua"', max_length=200, verbose_name='ubicación')),
                ('year', models.PositiveIntegerField(verbose_name='año')),
                ('description_short', models.CharField(blank=True, help_text='Para cards y listados. Máximo 300 caracteres.', max_length=300, verbose_name='descripción corta')),
                ('body', models.JSONField(blank=True, default=list, help_text='Bloques de contenido reusables (mismos que las páginas).', verbose_name='contenido')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado en home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.category', verbose_name='categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cover_photo', models.ForeignKey(blank=True, db_constraint=False, help_text='Si está vacía, se usa la primera foto de la galería.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.workphoto', verbose_name='foto de portada')),
            ],
            options={
                'verbose_name': 'historical obra',
                'verbose_name_plural': 'historical obras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
