# Generated by Django 5.2.16 on 2026-07-14 01:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría de FAQ',
                'verbose_name_plural': 'categorías de FAQ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_published', models.BooleanField(default=True, help_text='Por defecto sí: si lo creás, querés que se vea.', verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='faqs.faqcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['category__order', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFAQ',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_published', models.BooleanField(default=True, help_text='Por defecto sí: si lo creás, querés que se vea.', verbose_name='publicado')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='faqs.faqcategory', verbose_name='categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pregunta frecuente',
                'verbose_name_plural': 'historical preguntas frecuentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
