# Generated by Django 5.2.16 on 2026-07-14 01:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestimonial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('client_role', models.CharField(blank=True, help_text='Ej: "Gerente de proyecto"', max_length=200, verbose_name='cargo')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('client_photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto del cliente')),
                ('quote', models.TextField(help_text='La cita textual del cliente.', verbose_name='cita')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_work', models.ForeignKey(blank=True, db_constraint=False, help_text='Opcional. Si se borra la obra, el testimonio sobrevive.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portfolio.portfoliowork', verbose_name='obra relacionada')),
            ],
            options={
                'verbose_name': 'historical testimonio',
                'verbose_name_plural': 'historical testimonios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('client_role', models.CharField(blank=True, help_text='Ej: "Gerente de proyecto"', max_length=200, verbose_name='cargo')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='foto del cliente')),
                ('quote', models.TextField(help_text='La cita textual del cliente.', verbose_name='cita')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_work', models.ForeignKey(blank=True, help_text='Opcional. Si se borra la obra, el testimonio sobrevive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.portfoliowork', verbose_name='obra relacionada')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
